### ISSUE TITLE
Navigation is confusing and cumbersome

### ISSUE THREAD

**Issue by mrusme** [fedeztk/got#1]
Hey there, love this tool! 

It's super useful, unfortunately the navigation is extremely cumbersome and confusing. From what I see, one needs to press `Tab` to switch to "Language selection" first (which isn't obvious, because it doesn't say how to change tabs anywhere), then use `/` to search for a language (fyi, typing `es` to find Spanish won't work, even though that's the short code for it), then type `s` to select it as source, then type `/` again, type `eng`, and then type `t` to select it as target, then press `Shift+Tab` (again, not obvious) to switch back to text input and only then actually type the text.

I believe it would make more sense to get rid of the second tab and have e.g. `C-f` ("from") and `C-t` ("to") as global key bindings, which would allow for selecting the source/target language from a "popup"/modal using basically the same idea as right now (search with `/`).

Also, it would be nice if the translation tab would display the translated text underneath "Translated text:" (-> add `\n\n`) and support a shortcut like `yy` to copy the translation to the clipboard.

Thank you very much for your effort of building this!

**Comment by fedeztk** [comment]
First of all thank you for the feedback, I really appreciate it.

I agree with you, key bindings are not discoverable right now, and navigation is sub optimal to say at least.

I'll consider the popup approach in the near future, seems like a good idea. I'll experiment in a separate branch and update here with progresses/considerations.

**Comment by dagbdagb** [comment]
So, not sure if I have the samme or a different issue. I cannot figure out how to select source and target language independently. I always end up with es -> es or en-> en.    What about the UI am I missing?

**Comment by fedeztk** [comment]
In order to address poor keys discoverability, on [this](https://github.com/fedeztk/got/tree/feature/helpmenu) branch I added a global helpmenu:
![image](https://user-images.githubusercontent.com/58485208/173406513-5274979e-afdf-495a-bd54-14886bb80c5a.png)
I'm a bit concerned about having two helps in "language selection" tab:
![image](https://user-images.githubusercontent.com/58485208/173407205-0eef88c5-1f16-4b87-ad58-e03627fa2da7.png)
Other than that I think I'll merge this soon.

**Comment by fedeztk** [comment]
I am closing this since I consider those issues fixed with the merge of #22 
Please reopen if that is not the case or for further discussion.
