### ISSUE TITLE
[Error] invalid character '<' when introducing a one-word-string input

### ISSUE THREAD

**Issue by EPadronU** [fedeztk/got#10]
Here is a simple example
```bash
❯ got -o -f es -t en "adiós"
invalid character '<' looking for beginning of value
```

Replacing the acute `ó` by normal/ascii `o` seen to work
```bash
❯ got -o -f es -t en "adios"                                                                           ─╯
Translated text: adios

Part of speech: noun

- adieu: adiós, despedida
```

Another example
```bash
❯ got -o -f es -t en "té"
invalid character '<' looking for beginning of value
```

It works fine for a sentence
```bash
❯ got -o -f es -t en "¿Qué haces?" 
Translated text: What are you doing?

Part of speech: phrase

- What do you do?: ¿Qué haces?
```

Update:
I found just by chance another input that produces the same error but it does not have acute vowels:
```bash
❯ got -o -f es -t en "meta"
invalid character '<' looking for beginning of value
```

- Engine: Google
- Version: 2a5b336c (`got -v` don't show a thing. since I just installed I could assume I have the last current commit)

```bash
find . -iname '*got@v*'
./mod/cache/download/sumdb/sum.golang.org/lookup/github.com/fedeztk/got@v0.0.0-20220508213154-2a5b336c5e7e
./mod/github.com/fedeztk/got@v0.0.0-20220508213154-2a5b336c5e7e
```

**Comment by fedeztk** [comment]
Thanks for the report!
This was caused by unhandled errors from the API. The error still occurs (since I can't do anything about the engine implementation) but now doesn't crash and displays an error instead.
Reopen in case something isn't clear. Relevant changes are shown in #13
