### ISSUE TITLE
[Error] Simple word with no extra information is not translated

### ISSUE THREAD

**Issue by EPadronU** [fedeztk/got#12]
It looks like when a simple (with no extra information being provided by the engine) word is used as a input, the translation does not occurred.

This is the only example I've found so far:
```bash
❯ got -o -f es -t en "hola"
Translated text: hola 
```

- Engine: Google
- Version: 2a5b336c (`got -v` don't show a thing. since I just installed I could assume I have the last current commit)

**Comment by fedeztk** [comment]
Unfortunately I can't do much about the response from the API, this kind of error should be reported directly to [simplytranslate's repo](https://codeberg.org/SimpleWeb/SimplyTranslate-Engines)

**Comment by fedeztk** [comment]
This is no longer relevant since the new backend seems to work well with those cases as well.

As an example here is the output from the same command:
![image](https://github.com/fedeztk/got/assets/58485208/ee579690-656c-4380-aab7-39529e6025c6)

Feel free to reopen if needed.
