### ISSUE TITLE
Shortcut to reverse target/source language + Multi language support

### ISSUE THREAD

**Issue by Estebiu** [fedeztk/got#19]
The same way we have the "s" and the "t" shortcut to choose the source and the target's language, It will be awesome if we could switch this two languages with a shortcut, let's say "r". So now if we choose english as the source ant french as the target and press "r", now we'll have french as the source and english as the target languages.

My second improvement would be to add support to 2 or more languages: it'd be awesome if we could add 2 or more languages as the targets, to have multiples translations at the same time. It would be super useful if we are studying a new language when you're already fluent in other 2 (or more) languages. It's a feature that I always wanted on google translate but.. well.. never got.

**Comment by fedeztk** [comment]
Thanks for the feedback.

Language inversion/revert is something already planned since I needed that from the beginning. I just did not have enough time to develop it.
It will come soon.

On the other hand, multi language support is interesting but I do not think it is a feature worth investing since it seems more of a "niche" usage and not a core translator feature.

**Comment by Estebiu** [comment]
You added the reverse feature rather quickly, I'm impressed. And also, too bad for the absence of the multi language, I guess..

**Comment by fedeztk** [comment]
If I'll come up with a decent implementation I may add it in future. Right now I can't think of a non-breaking implementation (that practically would not change general program's behavior, like e.g. languages selection).

Thanks for the feedback.

**Comment by Estebiu** [comment]
Yeah, I got it. No problem.
Btw, another little bug is that when translating like a long phrase, the translated text will show in only one line so part of it may be unreadable.
