### ISSUE TITLE
App is no longer functional - simplytranslate.org no longer exists?

### ISSUE THREAD

**Issue by Devnol** [fedeztk/got#23]
Title basically says it all, got doesn't work anymore because simplytranslate seems to have disappeared

**Comment by fedeztk** [comment]
Sorry for the very late reply. It seems indeed that simplytranslate is no longer available.
As soon as I find a functional (and free) backend I will move to it and adapt the current codebase. I'm open to any suggestions.

Thanks for your patience.

**Comment by fedeztk** [comment]
This should be fixed thanks to #24.
There is now a new backend (lingvatranslate). Simplytranslate code is still there just in case it comes up again.

I'll close this issue for now but please reopen if you have any other question.
