### ISSUE TITLE
 dial tcp: lookup lingva.ml: no such host

### ISSUE THREAD

**Issue by gedw99** [fedeztk/got#25]
```sh
got -o -s en -t it "Hello World" 
Get "https://lingva.ml/api/v1//en/it/Hello+World": dial tcp: lookup lingva.ml: no such host

```

**Comment by fedeztk** [comment]
Thank you for reporting this, unfortunately lingva.ml is temporarily down.

I will consider using [different endpoints](https://github.com/thedaviddelta/lingva-translate#instances) in case it doesn't come up quickly enough.

**Comment by fedeztk** [comment]
No longer relevant since the host is up again. 

Please reopen if you encounter similar issues, thanks.
